<center><img src="car.jpg" width=500></center>


Insurance companies invest a lot of time and money into optimizing their pricing and accurately estimating the likelihood that customers will make a claim. In many countries insurance it is a legal requirement to have car insurance in order to drive a vehicle on public roads, so the market is very large!

(`Source: https://www.accenture.com/_acnmedia/pdf-84/accenture-machine-leaning-insurance.pdf`) 

Knowing all of this, On the Road car insurance have requested your services in building a model to predict whether a customer will make a claim on their insurance during the policy period. As they have very little expertise and infrastructure for deploying and monitoring machine learning models, they've asked you to identify the single feature that results in the best performing model, as measured by accuracy, so they can start with a simple model in production.

They have supplied you with their customer data as a csv file called `car_insurance.csv`, along with a table detailing the column names and descriptions below.



## The dataset

| Column | Description |
|--------|-------------|
| `id` | Unique client identifier |
| `age` | Client's age: <br> <ul><li>`0`: 16-25</li><li>`1`: 26-39</li><li>`2`: 40-64</li><li>`3`: 65+</li></ul> |
| `gender` | Client's gender: <br> <ul><li>`0`: Female</li><li>`1`: Male</li></ul> |
| `driving_experience` | Years the client has been driving: <br> <ul><li>`0`: 0-9</li><li>`1`: 10-19</li><li>`2`: 20-29</li><li>`3`: 30+</li></ul> |
| `education` | Client's level of education: <br> <ul><li>`0`: No education</li><li>`1`: High school</li><li>`2`: University</li></ul> |
| `income` | Client's income level: <br> <ul><li>`0`: Poverty</li><li>`1`: Working class</li><li>`2`: Middle class</li><li>`3`: Upper class</li></ul> |
| `credit_score` | Client's credit score (between zero and one) |
| `vehicle_ownership` | Client's vehicle ownership status: <br><ul><li>`0`: Does not own their vehilce (paying off finance)</li><li>`1`: Owns their vehicle</li></ul> |
| `vehcile_year` | Year of vehicle registration: <br><ul><li>`0`: Before 2015</li><li>`1`: 2015 or later</li></ul> |
| `married` | Client's marital status: <br><ul><li>`0`: Not married</li><li>`1`: Married</li></ul> |
| `children` | Client's number of children |
| `postal_code` | Client's postal code | 
| `annual_mileage` | Number of miles driven by the client each year |
| `vehicle_type` | Type of car: <br> <ul><li>`0`: Sedan</li><li>`1`: Sports car</li></ul> |
| `speeding_violations` | Total number of speeding violations received by the client | 
| `duis` | Number of times the client has been caught driving under the influence of alcohol |
| `past_accidents` | Total number of previous accidents the client has been involved in |
| `outcome` | Whether the client made a claim on their car insurance (response variable): <br><ul><li>`0`: No claim</li><li>`1`: Made a claim</li></ul> |

In [8]:
# Import required modules
import pandas as pd
import numpy as np
from statsmodels.formula.api import logit

# Start coding!

In [9]:
#Ignore all warnings
import warnings
warnings.filterwarnings('ignore')
warnings.filterwarnings(action='ignore', category=DeprecationWarning)

In [10]:
#Import car_insurance.csv file
car_insurance = pd.read_csv('car_insurance.csv')
print(car_insurance.info())
print(car_insurance.value_counts('outcome'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   10000 non-null  int64
 1   age                  10000 non-null  int64
 2   gender               10000 non-null  int64
 3   driving_experience   10000 non-null  object
 4   education            10000 non-null  object
 5   income               10000 non-null  object
 6   credit_score         9018 non-null   float64
 7   vehicle_ownership    10000 non-null  float64
 8   vehicle_year         10000 non-null  object
 9   married              10000 non-null  float64
 10  children             10000 non-null  float64
 11  postal_code          10000 non-null  int64
 12  annual_mileage       9043 non-null   float64
 13  vehicle_type         10000 non-null  object
 14  speeding_violations  10000 non-null  int64
 15  duis                 10000 non-null  int64
 16  past_accidents       10000 non-null  int64
 17  outcome              10000 non-null  float64
dtypes: float64(6), int64(7), object(5)
memory usage: 1.4+ MB
None
outcome
0.0    6867
1.0    3133
dtype: int64

In [11]:
#Fit a logistic regression of 'outcome' vs 'age' using car_insurance dataset
mdl_outcome_vs_age = logit('outcome ~ age', data = car_insurance).fit()
print(mdl_outcome_vs_age.params)

#Create confusion matrix for determining the accuracy
confusion_matrix = mdl_outcome_vs_age.pred_table()
print(confusion_matrix)
true_negative = confusion_matrix[0,0]
print(true_negative)
true_positive = confusion_matrix[1,1]
print(true_positive)
false_negative = confusion_matrix[1,0]
print(false_negative)
false_positive = confusion_matrix[0,1]
print(false_positive)
accuracy = (true_positive + true_negative)/(true_positive + true_negative + false_positive + false_negative)
print(accuracy)

Optimization terminated successfully.
         Current function value: 0.511794
         Iterations 6
Intercept    0.673040
age         -1.135579
dtype: float64
[[6299.  568.]
 [1685. 1448.]]
6299.0
1448.0
1685.0
568.0
0.7747

In [12]:
#Column names
print(car_insurance.columns)
print(car_insurance.keys())

#Initialize an empty DataFrame for collecting the accuracy values with column names
accuracy_df = pd.DataFrame()
accuracy_list = []
x_list = []

#Write loop
for x in car_insurance.keys():
    mdl_outcome_vs_x = logit('outcome ~ ' + x, data = car_insurance).fit()
    confusion_matrix = mdl_outcome_vs_x.pred_table()
    TP = confusion_matrix[1,1]
    TN = confusion_matrix[0,0]
    FP = confusion_matrix[0,1]
    FN = confusion_matrix[1,0]
    accuracy = (TP + TN) / (TP + TN + FP +FN)
    print(accuracy, x)
    #appending to the list
    accuracy_list.append(accuracy)
    x_list.append(x)

#Add the lists to the DataFrame
accuracy_df['accuracy'] = accuracy_list
accuracy_df['x_list'] = x_list
print(accuracy_df)

#Sort values based on the accuracy
accuracy_df.sort_values('accuracy', ascending = False)

Index(['id', 'age', 'gender', 'driving_experience', 'education', 'income',
       'credit_score', 'vehicle_ownership', 'vehicle_year', 'married',
       'children', 'postal_code', 'annual_mileage', 'vehicle_type',
       'speeding_violations', 'duis', 'past_accidents', 'outcome'],
      dtype='object')
Index(['id', 'age', 'gender', 'driving_experience', 'education', 'income',
       'credit_score', 'vehicle_ownership', 'vehicle_year', 'married',
       'children', 'postal_code', 'annual_mileage', 'vehicle_type',
       'speeding_violations', 'duis', 'past_accidents', 'outcome'],
      dtype='object')
Optimization terminated successfully.
         Current function value: 0.621660
         Iterations 4
0.6867 id
Optimization terminated successfully.
         Current function value: 0.511794
         Iterations 6
0.7747 age
Optimization terminated successfully.
         Current function value: 0.615951
         Iterations 5
0.6867 gender
Optimization terminated successfully.
         Current function value: 0.467092
         Iterations 8
0.7771 driving_experience
Optimization terminated successfully.
         Current function value: 0.603742
         Iterations 5
0.6867 education
Optimization terminated successfully.
         Current function value: 0.531499
         Iterations 6
0.7425 income
Optimization terminated successfully.
         Current function value: 0.567469
         Iterations 6
0.7066977156797516 credit_score
Optimization terminated successfully.
         Current function value: 0.552412
         Iterations 5
0.7351 vehicle_ownership
Optimization terminated successfully.
         Current function value: 0.572668
         Iterations 6
0.6867 vehicle_year
Optimization terminated successfully.
         Current function value: 0.586659
         Iterations 5
0.6867 married
Optimization terminated successfully.
         Current function value: 0.595431
         Iterations 5
0.6867 children
Optimization terminated successfully.
         Current function value: 0.617345
         Iterations 5
0.6867 postal_code
Optimization terminated successfully.
         Current function value: 0.601906
         Iterations 5
0.6933539754506248 annual_mileage
Optimization terminated successfully.
         Current function value: 0.621700
         Iterations 5
0.6867 vehicle_type
Optimization terminated successfully.
         Current function value: 0.558922
         Iterations 7
0.6867 speeding_violations
Optimization terminated successfully.
         Current function value: 0.598699
         Iterations 6
0.6867 duis
Optimization terminated successfully.
         Current function value: 0.549220
         Iterations 7
0.6867 past_accidents
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.000000
         Iterations: 35
1.0 outcome
    accuracy               x_list
0   0.686700                   id
1   0.774700                  age
2   0.686700               gender
3   0.777100   driving_experience
4   0.686700            education
5   0.742500               income
6   0.706698         credit_score
7   0.735100    vehicle_ownership
8   0.686700         vehicle_year
9   0.686700              married
10  0.686700             children
11  0.686700          postal_code
12  0.693354       annual_mileage
13  0.686700         vehicle_type
14  0.686700  speeding_violations
15  0.686700                 duis
16  0.686700       past_accidents
17  1.000000              outcome

    accuracy               x_list
17  1.000000              outcome
3   0.777100   driving_experience
1   0.774700                  age
5   0.742500               income
7   0.735100    vehicle_ownership
6   0.706698         credit_score
12  0.693354       annual_mileage
16  0.686700       past_accidents
15  0.686700                 duis
14  0.686700  speeding_violations
13  0.686700         vehicle_type
0   0.686700                   id
11  0.686700          postal_code
10  0.686700             children
8   0.686700         vehicle_year
4   0.686700            education
2   0.686700               gender
9   0.686700              married

In [13]:
#Column names
print(car_insurance.columns)
print(car_insurance.keys())

#Initialize an empty Dictionary for collecting the accuracy values with column names
accuracy_dict = {}

#Write loop
for key in car_insurance.keys():
    mdl_outcome_vs_key = logit('outcome ~ ' + key, data = car_insurance).fit()
    confusion_matrix = mdl_outcome_vs_key.pred_table()
    TP = confusion_matrix[1,1]
    TN = confusion_matrix[0,0]
    FP = confusion_matrix[0,1]
    FN = confusion_matrix[1,0]
    accuracy = (TP + TN) / (TP + TN + FP +FN)
    print(accuracy, key)
    accuracy_dict[key] = accuracy
print(accuracy_dict)

#Make DataFrame with values 
best_feature_df = pd.DataFrame()
best_feature_df['best_feature'] = 'driving_experience'
best_feature_df['best_accuracy'] = 0.7771



#Extract maximum accuracy (value) using loop
#Initializing the max accuracy as a counter
max_accuracy = 0

#Write loop for excluding outcome
for key in accuracy_dict.keys():
    if key != 'outcome':
        if accuracy_dict[key] > max_accuracy:    #value by value comparison to find the maximum
            max_accuracy = accuracy_dict[key]
            print(max_accuracy)
print(max_accuracy)            

#Extract best feature using loop to find the key associated with max accuracy
best_feature = ''

for key in accuracy_dict.keys():
    if accuracy_dict[key] == max_accuracy:
        best_feature = key

print(best_feature)


best_feature_df = pd.DataFrame()
best_feature_df['best_feature'] = [best_feature]
best_feature_df['best_accuracy'] = [max_accuracy]


best_feature_df

Index(['id', 'age', 'gender', 'driving_experience', 'education', 'income',
       'credit_score', 'vehicle_ownership', 'vehicle_year', 'married',
       'children', 'postal_code', 'annual_mileage', 'vehicle_type',
       'speeding_violations', 'duis', 'past_accidents', 'outcome'],
      dtype='object')
Index(['id', 'age', 'gender', 'driving_experience', 'education', 'income',
       'credit_score', 'vehicle_ownership', 'vehicle_year', 'married',
       'children', 'postal_code', 'annual_mileage', 'vehicle_type',
       'speeding_violations', 'duis', 'past_accidents', 'outcome'],
      dtype='object')
Optimization terminated successfully.
         Current function value: 0.621660
         Iterations 4
0.6867 id
Optimization terminated successfully.
         Current function value: 0.511794
         Iterations 6
0.7747 age
Optimization terminated successfully.
         Current function value: 0.615951
         Iterations 5
0.6867 gender
Optimization terminated successfully.
         Current function value: 0.467092
         Iterations 8
0.7771 driving_experience
Optimization terminated successfully.
         Current function value: 0.603742
         Iterations 5
0.6867 education
Optimization terminated successfully.
         Current function value: 0.531499
         Iterations 6
0.7425 income
Optimization terminated successfully.
         Current function value: 0.567469
         Iterations 6
0.7066977156797516 credit_score
Optimization terminated successfully.
         Current function value: 0.552412
         Iterations 5
0.7351 vehicle_ownership
Optimization terminated successfully.
         Current function value: 0.572668
         Iterations 6
0.6867 vehicle_year
Optimization terminated successfully.
         Current function value: 0.586659
         Iterations 5
0.6867 married
Optimization terminated successfully.
         Current function value: 0.595431
         Iterations 5
0.6867 children
Optimization terminated successfully.
         Current function value: 0.617345
         Iterations 5
0.6867 postal_code
Optimization terminated successfully.
         Current function value: 0.601906
         Iterations 5
0.6933539754506248 annual_mileage
Optimization terminated successfully.
         Current function value: 0.621700
         Iterations 5
0.6867 vehicle_type
Optimization terminated successfully.
         Current function value: 0.558922
         Iterations 7
0.6867 speeding_violations
Optimization terminated successfully.
         Current function value: 0.598699
         Iterations 6
0.6867 duis
Optimization terminated successfully.
         Current function value: 0.549220
         Iterations 7
0.6867 past_accidents
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.000000
         Iterations: 35
1.0 outcome
{'id': 0.6867, 'age': 0.7747, 'gender': 0.6867, 'driving_experience': 0.7771, 'education': 0.6867, 'income': 0.7425, 'credit_score': 0.7066977156797516, 'vehicle_ownership': 0.7351, 'vehicle_year': 0.6867, 'married': 0.6867, 'children': 0.6867, 'postal_code': 0.6867, 'annual_mileage': 0.6933539754506248, 'vehicle_type': 0.6867, 'speeding_violations': 0.6867, 'duis': 0.6867, 'past_accidents': 0.6867, 'outcome': 1.0}
0.6867
0.7747
0.7771
0.7771
driving_experience

         best_feature  best_accuracy
0  driving_experience         0.7771